# Generated by Django 5.1.7 on 2025-04-04 20:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuestionBank', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(max_length=255)),
                ('is_correct', models.BooleanField(default=False)),
                ('matching_text', models.CharField(blank=True, help_text='The matching pair text for matching questions', max_length=255, null=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Order of display')),
            ],
            options={
                'verbose_name': 'Public Question Choice',
                'verbose_name_plural': 'Public Question Choices',
                'ordering': ['order'],
            },
        ),
        migrations.RemoveField(
            model_name='choice',
            name='question',
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'verbose_name': 'Question', 'verbose_name_plural': 'Questions'},
        ),
        migrations.AlterUniqueTogether(
            name='topic',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='question',
            name='added_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contributed_questions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='question',
            name='is_verified',
            field=models.BooleanField(db_index=True, default=False, help_text='Verified by admin/teacher'),
        ),
        migrations.AddField(
            model_name='question',
            name='model_answer',
            field=models.TextField(blank=True, help_text='Model answer or grading criteria'),
        ),
        migrations.AddField(
            model_name='question',
            name='times_used',
            field=models.PositiveIntegerField(default=0, help_text='Number of times used in quizzes'),
        ),
        migrations.AddField(
            model_name='question',
            name='topics',
            field=models.ManyToManyField(related_name='questions', to='QuestionBank.topic'),
        ),
        migrations.AddField(
            model_name='topic',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='difficulty',
            field=models.CharField(choices=[('EASY', 'Easy'), ('MEDIUM', 'Medium'), ('HARD', 'Hard'), ('VERY_HARD', 'Very Hard')], db_index=True, default='MEDIUM', max_length=10),
        ),
        migrations.AlterField(
            model_name='question',
            name='duration',
            field=models.PositiveIntegerField(help_text='Duration in seconds'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('MCQ', 'Multiple Choice'), ('TF', 'True/False'), ('SHORT', 'Short Answer'), ('ESSAY', 'Essay'), ('MATCH', 'Matching')], db_index=True, default='MCQ', max_length=10),
        ),
        migrations.AlterField(
            model_name='question',
            name='subject',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='topic',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['subject', 'difficulty'], name='QuestionBan_subject_c49b2a_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['question_type', 'difficulty'], name='QuestionBan_questio_f09f8b_idx'),
        ),
        migrations.AddField(
            model_name='questionchoice',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='QuestionBank.question'),
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='question',
        ),
    ]
