# Generated by Django 5.1.7 on 2025-04-17 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('QuestionBank', '0004_questionbank'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QuestionBank',
        ),
    ]
